Repository IntelPython/dpnp, pull requests merged in 2020-11, with the labels that each got.

#208 Windows: linking with dpcpp, build scripts
  1.build.bat
  1.env.bat
  setup.py
  utils/command_build_clib.py
Labels: in progress

#278 DOCS align docstring for full with template
  dpnp/dpnp_iface_arraycreation.py
Labels: documentation

#279 DOCS add recommendations how to write docstrings
  doc/docstring_template.py
Labels: documentation

#282 DOCS align docstring of space-like functions with template
  dpnp/dpnp_iface_arraycreation.py
Labels: documentation

#280 DOCS align docstring for counting_nonzero with template
  dpnp/dpnp_iface_counting.py
Labels: documentation

#283 DOCS align docstring for ones-like functions with template
  dpnp/dpnp_iface_arraycreation.py
Labels: documentation

#284 DOCS align docstring for zeros-like functions with template
  dpnp/dpnp_iface_arraycreation.py
Labels: documentation

#290 DOCS align docstring for bitwise functions with template
  dpnp/dpnp_iface_bitwise.py
Labels: documentation

#297 DOCS change docstring template
  doc/conf.py
  doc/docstring_template.py
  doc/reference/difference.rst
Labels: documentation

#298 DOCS align docstrings for array creation funcs with template
  dpnp/dpnp_iface_arraycreation.py
Labels: documentation

#299 DOCS align docstrings for bitwise operations with template
  dpnp/dpnp_iface_bitwise.py
Labels: documentation

#302 DOCS align docstring for erf with template
  doc/reference/index.rst
  doc/reference/special.rst
  dpnp/dpnp_iface_arraycreation.py
  dpnp/dpnp_iface_libmath.py
Labels: documentation

#303 DOCS align docstrings for linearalgebra module with template
  dpnp/dpnp_iface_linearalgebra.py
Labels: documentation

#304 DOCS align docstring for count_nonzero with template
  dpnp/dpnp_iface_counting.py
Labels: documentation

#305 DOCS align docstrings for logic funcs with template
  doc/reference/difference.rst
  dpnp/dpnp_iface_logic.py
Labels: documentation

#306 DOCS align docstring for manipulation funcs with template
  dpnp/dpnp_iface_manipulation.py
Labels: documentation

#311 DOCS align docstring for sorting funcs with template
  dpnp/dpnp_iface_sorting.py
Labels: documentation

#312 DOCS align docstring for statistics funcs with template
  dpnp/dpnp_iface_statistics.py
Labels: documentation

#314 DOCS align docstring for trigonometric funcs with template
  doc/docstring_template.py
  dpnp/backend_trigonometric.pyx
  dpnp/dpnp_iface_linearalgebra.py
  dpnp/dpnp_iface_manipulation.py
  dpnp/dpnp_iface_searching.py
  dpnp/dpnp_iface_statistics.py
  dpnp/dpnp_iface_trigonometric.py
Labels: documentation

#315 DOCS align some docstring with template
  doc/reference/manipulation.rst
  dpnp/dpnp_iface.py
  dpnp/dpnp_iface_types.py
Labels: documentation

#316 DOCS align docstring for asfarray and nonzero with template
  doc/reference/manipulation.rst
  dpnp/dpnp_iface_arraymanipulation.py
  dpnp/dpnp_iface_indexing.py
Labels: documentation

#318 DOCS align docstring for mathematical module with template
  dpnp/dpnp_iface_mathematical.py
Labels: documentation, in progress
